#!/bin/sh
echo "start code-server"
code-server &

sleep 5s

echo "adding extentions ... "
cd /root/.local/share/code-server/extensions
cp /extensions.tar.bz2 ./
tar -jxf extensions.tar.bz2
cp .plorefice.devicetree.tar.bz2 ./
tar -jxf plorefice.devicetree.tar.bz2
rm extensions.tar.bz2
echo "done!"

echo "custom settings ... "
cp -rf /settings.json /root/.local/share/code-server/User/
echo "done!"


# execute the CMD
echo "run bash."
exec "$@"
