#!/bin/sh

echo "adding extentions ... "
cp extensions.tar.bz2 /usr/local/bin/code-server/extensions/
cd /usr/local/bin/code-server/extensions
tar -jxf extensions.tar.bz2 
rm extensions.tar.bz2

echo "adding extentions, done!"
